/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.socialmedia;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ebrar
 */
public class NewAccount_frm extends javax.swing.JFrame {

    /**
     * Creates new form newAccount
     */
    public NewAccount_frm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        pswrd_password2 = new javax.swing.JPasswordField();
        pswrd_password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_signUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nickname = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        spnr_age = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        lbl_ageControl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbx_city = new javax.swing.JComboBox<>();
        cbx_sure = new javax.swing.JCheckBox();
        lbl_nameSurname = new javax.swing.JLabel();
        lbl_nickname = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(181, 166, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Create an account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 48))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(520, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 690));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Name Surname:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("R-Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Gender:");

        buttonGroup1.add(rbtn_male);
        rbtn_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtn_male.setText("Male");
        rbtn_male.setOpaque(false);

        buttonGroup1.add(rbtn_female);
        rbtn_female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtn_female.setText("Female");
        rbtn_female.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Mail:");

        btn_signUp.setBackground(new java.awt.Color(204, 204, 255));
        btn_signUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_signUp.setText("Sign Up");
        btn_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signUpMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Nickname:");

        btn_cancel.setBackground(new java.awt.Color(204, 204, 255));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });

        spnr_age.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Age:");

        lbl_ageControl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ageControl.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ageControl.setText("CHECK");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("City:");

        cmbx_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce" }));
        cmbx_city.setSelectedIndex(-1);

        cbx_sure.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbx_sure.setText("I am sure I want to register");
        cbx_sure.setOpaque(false);

        lbl_nameSurname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nameSurname.setForeground(new java.awt.Color(204, 0, 0));
        lbl_nameSurname.setText("CHECK");

        lbl_nickname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nickname.setForeground(new java.awt.Color(204, 0, 0));
        lbl_nickname.setText("CHECK");

        lbl_mail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(204, 0, 0));
        lbl_mail.setText("CHECK");

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(204, 0, 0));
        lbl_password.setText("CHECK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pswrd_password)
                                    .addComponent(pswrd_password2)
                                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbx_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_nickname)
                                    .addComponent(txt_nameSurname)
                                    .addComponent(txt_mail)
                                    .addComponent(lbl_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_nickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_nameSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(rbtn_male, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbtn_female))
                                            .addComponent(spnr_age, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                                    .addComponent(lbl_ageControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbx_sure)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lbl_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lbl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnr_age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lbl_ageControl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbx_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbtn_male)
                    .addComponent(rbtn_female))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pswrd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pswrd_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cbx_sure)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_signUp)
                    .addComponent(btn_cancel))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signUpMouseClicked
        String gender = null;
        String city = (String) cmbx_city.getSelectedItem();

        //I put a default profile photo when users sign up
        String file = "C:\\Users\\ebrar\\Documents\\SocialMedia\\src\\main\\java\\com\\mycompany\\socialmedia\\images\\profilepicture.jpg";

        if (MenuControl() == false) { //If the MenuControl returns false, it goes inside the if structur
            JOptionPane.showMessageDialog(this, "Please fill in all the blanks correctly");  //I suppress error message with JOptionpane
        } else { //If the MenuControl returns true, it goes inside the else structure.

            //I get the gender from the radiobutton
            if (rbtn_female.isSelected()) {
                gender = "Female";
            } else if (rbtn_male.isSelected()) {
                gender = "Male";
            }
            try {
                //I save all the information of the newly registered user to the database named Users with "Insert".
                Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Users", "SA", "as");
                Statement stmt = conn.createStatement();
                String query = "INSERT INTO SA.USERS VALUES('" + txt_nameSurname.getText() + "', '" + txt_nickname.getText() + "', '" + txt_mail.getText() + "', '" + city + "', '" + gender + "', '" + pswrd_password.getText() + "', '" + file + "')";
                stmt.executeUpdate(query);
                conn.close();

            } catch (SQLException ex) {
                Logger.getLogger(NewAccount_frm.class.getName()).log(Level.SEVERE, null, ex);
            }

            //I close the JFrame named NewAccount and open the LoginScreen JFrame.
            LoginScreen_frm lfrm = new LoginScreen_frm();
            this.setVisible(false);
            lfrm.setVisible(true);
        }
    }//GEN-LAST:event_btn_signUpMouseClicked

    public boolean MenuControl() {
        Boolean value = false; //I define boolean to return
        Matcher matcher; //I define matcher for regex

        //Name Surname control by regex 
        matcher = Pattern.compile("^([a-zA-Z(ıİşŞ)]{3,12})([a-zA-Z(ıİşŞ)]{3,12})?\\s[a-zA-Z(ıİşŞ)]{2,20}").matcher(txt_nameSurname.getText());
        if (txt_nameSurname.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_nameSurname.setText("Name surname must be like " + "name name2 surname");
            return value;
        } else {
            lbl_nameSurname.setForeground(Color.green);
            lbl_nameSurname.setText("APPROPRIATE");
        }

        //Nickname control by regex
        matcher = Pattern.compile("^[a-zA-Z(ıİşŞ)]{1,2}[\\S]{4,20}$").matcher(txt_nickname.getText());
        if (txt_nickname.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_nickname.setText("Nickname must be like " + "user,user12");
            return value;
        } else {
            lbl_nickname.setForeground(Color.green);
            lbl_nickname.setText("APPROPRIATE");
        }

        //Email control by regex
        matcher = Pattern.compile("^[a-zA-Z(ıİşŞ)][\\w\\d(ıİşŞ)]{2,20}[\\S]@(gmail|hotmail)(.com)$").matcher(txt_mail.getText());
        if (txt_mail.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_mail.setForeground(Color.red);
            lbl_mail.setText("Email must be like user@gmail(hotmail).com");
        } else {
            lbl_mail.setForeground(Color.green);
            lbl_mail.setText("APPROPRIATE");
        }

        //Age control
        int age = (int) spnr_age.getValue();
        if (13 > age) {
            lbl_ageControl.setText("Age cannot be less than 13");
            return value;
        } else {
            lbl_ageControl.setForeground(Color.green);
            lbl_ageControl.setText("APPROPRIATE");
        }

        //City control
        if (cmbx_city.getSelectedIndex() == -1) {
            return value;
        }

        //Gender control
        if (!(rbtn_female.isSelected() || rbtn_male.isSelected())) {
            return value;
        }

        //Password control by regex
        matcher = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{5,}$").matcher(pswrd_password.getText());
        if (pswrd_password.getText().isEmpty() || pswrd_password2.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_password.setForeground(Color.RED);
            lbl_password.setText("Password  must be like asdA1");
            return value;
        } else if (!(pswrd_password.getText().equals(pswrd_password2.getText()))) {
            lbl_password.setForeground(Color.red);
            lbl_password.setText("R-Password must match with password");
            return value;
        } else {
            lbl_password.setForeground(Color.green);
            lbl_password.setText("APPROPRIATE");
        }

        //Sure control
        if (!cbx_sure.isSelected()) {
            return value;
        }

        return true;
    }
    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        LoginScreen_frm lfrm = new LoginScreen_frm(); //I'm creating a LoginScreen object
        this.setVisible(false); //I'm closing this JFrame
        lfrm.setVisible(true); //I'm opening the LoginScreen JFrame.

    }//GEN-LAST:event_btn_cancelMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        LoginScreen_frm lfrm = new LoginScreen_frm(); //I'm creating a LoginScreen object
        this.setVisible(false); //I'm closing this JFrame
        lfrm.setVisible(true); //I'm opening the LoginScreen JFrame.

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_signUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbx_sure;
    private javax.swing.JComboBox<String> cmbx_city;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ageControl;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nameSurname;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JPasswordField pswrd_password;
    private javax.swing.JPasswordField pswrd_password2;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JSpinner spnr_age;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nameSurname;
    private javax.swing.JTextField txt_nickname;
    // End of variables declaration//GEN-END:variables
}
