/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.socialmedia;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ebrar
 */
public class UpdateProfile_frm extends javax.swing.JFrame {

    Profile_frm lfrm = new Profile_frm(); //I create object from Profile JFrame to return after update
    String nick; //I created a String for the user's nickname from the Profile JFrame

    /**
     * Creates new form UpdateProfile_frm
     */
    public UpdateProfile_frm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        pswrd_password2 = new javax.swing.JPasswordField();
        pswrd_password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_Update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nickname = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmbx_city = new javax.swing.JComboBox<>();
        cbx_sure = new javax.swing.JCheckBox();
        lbl_nameSurname = new javax.swing.JLabel();
        lbl_nickname = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(211, 195, 195));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 40))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 630));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Name Surname:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("R-Password:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Mail:");

        btn_Update.setBackground(new java.awt.Color(204, 204, 255));
        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Nickname:");

        txt_nickname.setEnabled(false);

        btn_cancel.setBackground(new java.awt.Color(204, 204, 255));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("City:");

        cmbx_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman", "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce" }));
        cmbx_city.setSelectedIndex(-1);

        cbx_sure.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbx_sure.setText("I am sure I want to update my profile");
        cbx_sure.setOpaque(false);

        lbl_nameSurname.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswrd_password, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(pswrd_password2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_nickname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nickname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbx_city, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                                .addComponent(lbl_nameSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nameSurname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addComponent(lbl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbx_sure)
                    .addComponent(jLabel11))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbx_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pswrd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pswrd_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbx_sure)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Update)
                    .addComponent(btn_cancel))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Information(String nickname) { //I'm pulling all the user's information from the database with the nickname.
        nick = nickname;
        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Users", "SA", "as");
            Statement stmt = conn.createStatement();

            //With "Select" I take all the data belonging to the nickname and put it in the appropriate places in the JFrame
            String query = "SELECT * FROM USERS WHERE nickname LIKE '%" + nickname + "%'";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                txt_nameSurname.setText(rs.getString("name"));
                txt_nickname.setText(rs.getString("nickname"));
                txt_mail.setText(rs.getString("mail"));
                cmbx_city.setSelectedItem(rs.getString("city"));
                pswrd_password.setText(rs.getString("password"));
                pswrd_password2.setText(rs.getString("password"));
            }
            conn.close();

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked

        if (MenuControl() == false) { //If the MenuControl returns false, it goes inside the if structure.
            JOptionPane.showMessageDialog(this, "Please fill in all the blanks correctly"); //I suppress error message with JOptionpane
        } else { //If the MenuControl returns true, it goes inside the else structure.
            try {
                //I save all the data returned from the components with the appropriate types
                String name = txt_nameSurname.getText();
                String mail = txt_mail.getText();
                String city = (String) cmbx_city.getSelectedItem();
                String password = pswrd_password.getText();

                //I update the data I received with "Update" in the Users database
                Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Users", "SA", "as");
                PreparedStatement ps = conn.prepareStatement("UPDATE USERS SET name = ?, mail = ?, city = ?, password = ? WHERE nickname = ?");

                ps.setString(1, name);
                ps.setString(2, mail);
                ps.setString(3, city);
                ps.setString(4, password);
                ps.setString(5, nick);

                ps.executeUpdate();
                conn.close();

            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "Profile updated successfully"); //I'm suppressing message with JOptionpane that the update was successful
            this.setVisible(false); //I'm closing this JFrame because the update process is finished
        }
    }//GEN-LAST:event_btn_UpdateMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false); //I'm closing this JFrame
    }//GEN-LAST:event_formWindowClosing

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.setVisible(false); //I'm closing this JFrame
    }//GEN-LAST:event_btn_cancelMouseClicked

    public boolean MenuControl() {
        Boolean value = false; //I define boolean to return
        Matcher matcher; //I define matcher for regex

        //Name Surname control by regex.
        matcher = Pattern.compile("^([a-zA-Z(ıİşŞ)]{3,12})([a-zA-Z(ıİşŞ)]{3,12})?\\s[a-zA-Z(ıİşŞ)]{2,20}").matcher(txt_nameSurname.getText());
        if (txt_nameSurname.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_nameSurname.setText("Name surname must be like " + "name name2 surname");
            return value;
        } else {
            lbl_nameSurname.setForeground(Color.green);
            lbl_nameSurname.setText("APPROPRIATE");
        }

        //Email control by regex
        matcher = Pattern.compile("^[a-zA-Z(ıİşŞ)][\\w\\d(ıİşŞ)][\\S]{2,20}@(gmail|hotmail)(.com)$").matcher(txt_mail.getText());
        if (txt_mail.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_mail.setForeground(Color.red);
            lbl_mail.setText("Email must be like user@gmail(hotmail).com");
        } else {
            lbl_mail.setForeground(Color.green);
            lbl_mail.setText("APPROPRIATE");
        }

        //City control
        if (cmbx_city.getSelectedIndex() == -1) {
            return value;
        }

        //Password control by regex
        matcher = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{5,}$").matcher(pswrd_password.getText());
        if (pswrd_password.getText().isEmpty() || pswrd_password2.getText().isEmpty()) {
            return value;
        } else if (!matcher.find()) {
            lbl_password.setForeground(Color.RED);
            lbl_password.setText("Password  must be like asdA1");
            return value;
        } else if (!(pswrd_password.getText().equals(pswrd_password2.getText()))) {
            lbl_password.setForeground(Color.red);
            lbl_password.setText("R-Password must match with password");
            return value;
        } else {
            lbl_password.setForeground(Color.green);
            lbl_password.setText("APPROPRIATE");
        }

        //Sure control
        if (!cbx_sure.isSelected()) {
            return value;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfile_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JCheckBox cbx_sure;
    private javax.swing.JComboBox<String> cmbx_city;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nameSurname;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JPasswordField pswrd_password;
    private javax.swing.JPasswordField pswrd_password2;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nameSurname;
    private javax.swing.JTextField txt_nickname;
    // End of variables declaration//GEN-END:variables
}
